//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a chocolate.
        /// </summary>
        internal static string Chocolate {
            get {
                return ResourceManager.GetString("Chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a coffee.
        /// </summary>
        internal static string Coffee {
            get {
                return ResourceManager.GetString("Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The drink type should be tea, coffee or chocolate..
        /// </summary>
        internal static string ErrorDrinkNotExist {
            get {
                return ResourceManager.GetString("ErrorDrinkNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} costs {1}..
        /// </summary>
        internal static string ErrorMoneyNotEnought {
            get {
                return ResourceManager.GetString("ErrorMoneyNotEnought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of sugars should be between 0 and 2..
        /// </summary>
        internal static string ErrorNumberOfSugars {
            get {
                return ResourceManager.GetString("ErrorNumberOfSugars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a extra hot.
        /// </summary>
        internal static string MessageExtraHot {
            get {
                return ResourceManager.GetString("MessageExtraHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have ordered a {0}.
        /// </summary>
        internal static string MessageOrdered {
            get {
                return ResourceManager.GetString("MessageOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a with {0} sugars(stick included)..
        /// </summary>
        internal static string MessageWithSugars {
            get {
                return ResourceManager.GetString("MessageWithSugars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tea.
        /// </summary>
        internal static string Tea {
            get {
                return ResourceManager.GetString("Tea", resourceCulture);
            }
        }
    }
}
